config/routes.rb
Rails.application.routes.draw do
  
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  root to: "catalog#index"
    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController
  include BlacklightAdvancedSearch::Controller

  include Blacklight::Catalog
  # This filter applies the hydra access controls
  #before_action :enforce_show_permissions, only: :show
  configure_blacklight do |config|
    # default advanced config values
    config.advanced_search ||= Blacklight::OpenStructWithHashAccess.new
    # config.advanced_search[:qt] ||= 'advanced'
    config.advanced_search[:url_key] ||= 'advanced'
    config.advanced_search[:query_parser] ||= 'dismax'
    config.advanced_search[:form_solr_parameters] ||= {}

    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      qt: 'search',
      rows: 10
    }

    # solr field configuration for search results/index views
    config.index.title_field = 'title_tesim'
    config.index.display_type_field = 'has_model_ssim'


    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _tsimed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    config.add_facet_field ( 'viewopt_ssi'),label: 'Viewopts'
    config.add_facet_field ('state_ssi') ,label:"State"
    #config.add_facet_field ('id') , label: 'Format'

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.default_solr_params[:'facet.field'] = config.facet_fields.keys
    #use this instead if you don't want to query facets marked :show=>false
    #config.default_solr_params[:'facet.field'] = config.facet_fields.select{ |k, v| v[:show] != false}.keys


    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field 'oid_isi', label: 'oid_isi'
    config.add_index_field 'id', label: 'id'
    config.add_index_field 'viewopt_ssi', label: 'Viewopt'
    config.add_index_field 'timestamp' , label: 'timestamp'
    config.add_index_field 'state_ssi' , label: 'state_ssi'
    config.add_index_field 'active_fedora_model_ssim' , label: 'active_fedora_model_ssim'
    #config.add_index_field
    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    #
    config.add_show_field 'oid_isi', label: 'oid_isi'
    config.add_show_field 'id', label: 'id'
    config.add_show_field 'viewopt_ssi', label: 'Viewopt'
    config.add_show_field 'timestamp' , label: 'timestamp'
    config.add_show_field 'state_ssi' , label: 'state_ssi'
    config.add_show_field 'active_fedora_model_ssim' , label: 'active_fedora_model_ssim'

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different.

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise.



    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields.
    #
    config.add_search_field 'all_fields', label: 'All Fields'

    config.add_search_field('oid_isi') do |field|
      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      field.solr_parameters = {
          qf: 'oid_isi',
          pf: 'oid_isi'
      }
    end

    config.add_search_field('id') do |field|
      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      field.solr_parameters = {
          qf: 'id',
          pf: 'id'
      }
    end


    config.add_search_field('title') do |field|
      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      field.solr_local_parameters = {
          qf: '$title_qf',
          pf: '$title_pf'
      }
    end


    # Specifying a :qt only to show it's possible, and so our internal automated
    # tests can test it. In this case it's the same as
    # config[:default_solr_parameters][:qt], so isn't actually neccesary.

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'oid_isi asc, title_tesi asc', label: 'oid_isi'
    config.add_sort_field 'id asc, title_tesi asc', label: 'id'
    config.add_sort_field 'score desc, pub_date_dtsi desc, title_tesi asc', label: 'relevance'


    # If there are more than this many search results, no spelling ("did you
    # mean") suggestion is offered.
    config.spell_max = 5
  end



end

app/views/catalog/_bookmark_control.html.erb
<% if current_or_guest_user %>
  <%-
  # Note these two forms are pretty similar but for different :methods, classes, and labels.
  # but it was simpler to leave them seperate instead of DRYing them, got confusing trying that.
  # the data-doc-id attribute is used by our JS that converts to a checkbox/label.
  -%>
  <% unless bookmarked? document %>

      <%= form_tag( bookmark_path( document ), :method => :put, :class => "bookmark_toggle", "data-doc-id" => document.id, :'data-present' => t('blacklight.search.bookmarks.present'), :'data-absent' => t('blacklight.search.bookmarks.absent'), :'data-inprogress' => t('blacklight.search.bookmarks.inprogress')) do %>
        <%= submit_tag(t('blacklight.bookmarks.add.button'), :id => "bookmark_toggle_#{document.id.to_s.parameterize}", :class => "bookmark_add btn btn-default") %>
      <% end %>

  <% else %>

      <%= form_tag( bookmark_path( document ), :method => :delete, :class => "bookmark_toggle", "data-doc-id" => document.id, :'data-present' => t('blacklight.search.bookmarks.present'), :'data-absent' => t('blacklight.search.bookmarks.absent'), :'data-inprogress' => t('blacklight.search.bookmarks.inprogress')) do %>
        <%= submit_tag(t('blacklight.bookmarks.remove.button'), :id => "bookmark_toggle_#{document.id.to_s.parameterize}", :class => "bookmark_remove btn btn-default") %>
      <% end %>

  <% end %>
<% else %>
  &nbsp;
<% end %>

app/views/catalog/_facet_limit.html.erb
<ul class="facet-values list-unstyled">
  <% paginator = facet_paginator(facet_field, display_facet) %>
  <%= render_facet_limit_list paginator, field_name %>

  <% unless paginator.last_page? || params[:action] == "facet" %>
    <li class="more_facets_link">
      <%= link_to t("more_#{field_name}_html", scope: 'blacklight.search.facets', default: :more_html, field_name: facet_field.label),
        search_facet_path(id: field_name), class: "more_facets_link" %>
    </li>
  <% end %>
</ul>

app/views/catalog/_facet_pagination.html.erb
<div class="prev_next_links btn-group pull-left">
  <%= link_to_previous_page @pagination, raw(t('views.pagination.previous')), params: search_state.to_h, param_name: blacklight_config.facet_paginator_class.request_keys[:page], class: 'btn btn-link', data: { ajax_modal: "preserve" } do %>
    <span class="disabled btn btn-disabled"><%= raw(t('views.pagination.previous')) %></span>
  <% end %>

  <%= link_to_next_page @pagination, raw(t('views.pagination.next')), params: search_state.to_h, param_name: blacklight_config.facet_paginator_class.request_keys[:page], class: 'btn btn-link',  data: { ajax_modal: "preserve" } do %>
    <span class="disabled btn  btn-disabled"><%= raw(t('views.pagination.next')) %></span>
  <% end %>
</div>

<div class="sort_options btn-group pull-right">
  <% if @pagination.sort == 'index' -%>
    <span class="active az btn btn-default"><%= t('blacklight.search.facets.sort.index') %></span>
    <%= link_to(t('blacklight.search.facets.sort.count'), @pagination.params_for_resort_url('count', search_state.to_h), class: "sort_change numeric btn btn-default", data: { ajax_modal: "preserve" }) %>
  <% elsif @pagination.sort == 'count' -%>
    <%=  link_to(t('blacklight.search.facets.sort.index'), @pagination.params_for_resort_url('index', search_state.to_h), class: "sort_change az btn btn-default",  data: { ajax_modal: "preserve" }) %>
    <span class="active numeric btn btn-default"><%= t('blacklight.search.facets.sort.count') %></span>
  <% end -%>
</div>

app/views/catalog/_facet_pivot.html.erb
<ul class="pivot-facet list-unstyled">
  <% display_facet.items.each do |item| -%>
    <li>
    <span class="facet-values">
    <% if facet_in_params?(field_name, item) %>
        <%= render_selected_facet_value(field_name, item) %>              
      <% else %>              
        <%= render_facet_value(field_name, item) %>              
    <% end -%>
    </span>

      <%= render partial: 'facet_pivot', locals: { display_facet: item, field_name: field_name, solr_field: field_name } %>
    </li>
  <% end %>

</ul>

app/views/catalog/_facets.html.erb
<% # main container for facets/limits menu -%>
<% if has_facet_values?  %>
<div id="facets" class="facets sidenav">

  <div class="top-panel-heading panel-heading">
    <button type="button" class="facets-toggle" data-toggle="collapse" data-target="#facet-panel-collapse">
      <span class="sr-only">Toggle facets</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <h2 class='facets-heading'>
      <%= t('blacklight.search.facets.title') %>
    </h2>
  </div>

  <div id="facet-panel-collapse" class="collapse panel-group">
    <%= render_facet_partials %>
  </div>
</div>
<% end %>

app/views/catalog/_home_text.html.erb
<div class="page-header row">
  <h2 class="col-md-8 page-heading"><%= t('blacklight.welcome') %></h2>
</div>

<div id="getting-started">
  <h3 class='section-heading'>Search based on &quotOIDs&quot or &quotIDs&quot</h3>

  <ol>
    <li><a href="https://github.com/projectblacklight/blacklight/wiki#blacklight-configuration">Configure Blacklight</a></li>
  </ol>
</div>

<%# This is the same panel shown in the Rails welcome template %>
<div id="about">
  <h3 class='section-heading'></h3>
  <div id="about-content" class="well" style="display: none"></div>
</div>

<script>
  $(function() {
    $('#about a').on('click', function(e) {
      e.preventDefault();

      if ($('#about-content').html() == "") {
        $('#about-content').load($(this).attr("href"), function() {
          $('#about-content').show();
        });
      } else {
        $('#about-content').toggle();
      }
    });
  });
</script>

app/views/catalog/_index_default.html.erb
<% doc_presenter = index_presenter(document) %>
<%# default partial to display solr document fields in catalog index view -%>
<dl class="document-metadata dl-horizontal dl-invert">

  <% index_fields(document).each do |field_name, field| -%>
  <!--done for weird formatting issue-->
    <% if should_render_index_field? document, field %>
        <!-- checks if field is null and if so displays empty-->
        <%@nofield = false %>

    <% else @nofield = true%>
    <% end -%>
    <dt class="blacklight-<%= field_name.parameterize %>"><%= render_index_field_label document, field: field_name %></dt>
    <dd class="blacklight-<%= field_name.parameterize %>"><%= (@nofield) ? '[]': (doc_presenter.field_value field) %></dd>
    <% if field_name == 'oid_isi' %>
      <dt class="blacklight-<%= field_name.parameterize %>"><%= render_index_field_label document, field: 'LadyBird' %></dt>
      <dd class="blacklight-<%= field_name.parameterize %>"><%= "http://ladybird.library.yale.edu/object_overview.aspx?qoid=#{field.value}"%></dd>
      <!-- FOR WHEN I KNOW OID GETS RETURNED
      dd class="blacklight-<%= field_name.parameterize %>"><%= link_to("Click Here","http://ladybird.library.yale.edu/object_overview.aspx?qoid=#{field.value}")%></dd-->
    <% end%>
  <% end -%>

</dl>

app/views/catalog/_index_header_default.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
    <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions document, wrapping_class: "index-document-functions col-sm-3 col-lg-2" %>
  <% end %>

  <h3 class="index_title document-title-heading <%= document_actions.present? ? "col-sm-9 col-lg-10" : "col-md-12" %>">
    <% if counter = document_counter_with_offset(document_counter) %>
      <span class="document-counter">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span>
    <% end %>
    <%= link_to_document document, document_show_link_field(document), counter: counter %>
  </h3>

  <%= document_actions %>
</div>

app/views/catalog/_search_form.html.erb
<%= form_tag search_action_url, method: :get, class: 'search-query-form clearfix navbar-form', role: 'search' do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
  <div class="input-group">
    <% if search_fields.length > 1 %>
      <span class="input-group-addon for-search-field">
        <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), title: t('blacklight.search.form.search_field.title'), id: "search_field", class: "search_field") %>
      </span>
    <% elsif search_fields.length == 1 %>
      <%= hidden_field_tag :search_field, search_fields.first.last %>
    <% end %>

    <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
    <%= text_field_tag :q, params[:q], placeholder: t('blacklight.search.form.search.placeholder'), class: "search_q q form-control", id: "q", autofocus: should_autofocus_on_search_box?, data: { autocomplete_enabled: autocomplete_enabled?, autocomplete_path: blacklight.suggest_index_path }  %>

    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary search-btn" id="search">
        <span class="submit-search-text"><%= t('blacklight.search.form.submit') %></span>
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </span>
  </div>
<% end %>

app/views/catalog/_search_results.html.erb
<h2 class="sr-only top-content-title"><%= t('blacklight.search.search_results_header') %></h2>

<% @page_title = t('blacklight.search.page_title.title', :constraints => render_search_to_page_title(params), :application_name => application_name) %>

<% content_for(:head) do -%>
  <%= render_opensearch_response_metadata %>
  <%= rss_feed_link_tag %>
  <%= atom_feed_link_tag %>
<% end %>

<%= render 'search_header' %>

<h2 class="sr-only"><%= t('blacklight.search.search_results') %></h2>

<%- if @response.empty? %>
  <%= render "zero_results" %>
<%- elsif render_grouped_response? %>
  <%= render_grouped_document_index %>
<%- else %>
  <%= render_document_index %>
<%- end %>

<%= render 'results_pagination' %>

app/views/catalog/_show_sidebar.html.erb
<%= render :partial => 'show_tools' %>

<dl class="dl-horizontal  dl-invert ladybird-info" id="ladybird-info">
  <dt>View More:</dt>
  <dd><button class="btn btn-primary moreinfo_link">Open</button></dd>
  <dd><% document = @document %> </dd>
</dl>
<script>
    $('.moreinfo_link').click( function() {
        $('#moreinfo-dialog').appendTo('body');
        $('#moreinfo-dialog').modal('show');
        return false;
    });
</script>
<!-- Modal -->
<div class="modal fade" id="moreinfo-dialog" tabindex="-1" role="dialog" aria-labelledby="moreinfo-dialog-title" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="moreinfo-dialog-title">More Info For <%= document['id'] %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
        </div>
        <div class="more-info-body">
          <ul>
              <li><span class="item-key"><%= "asdf" %></span> <span class="item-value"><%= "1"  %></span></li>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
<style>
  .item-key {
    font-weight: bold;
    display: inline-block;
    width: 200px;
  }
  .item-value {
  }
  .more-info-body {
    overflow: auto; max-height: 400px; margin-top: 10px
  }
  #ladybird-info  dt {
    float: left;
    text-align: right;
    margin-right: 5px;
  }
</style>
<% unless @document.more_like_this.empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">More Like This</div>
    <div class="panel-body">
      <%= render :collection => @document.more_like_this, :partial => 'show_more_like_this', :as => :document %>
    </div>
  </div>
<% end %>

app/views/catalog/index.html.erb
<div id="sidebar" class="<%= sidebar_classes %>">
  <%= render 'search_sidebar' %>
</div>

<div id="content" class="<%= main_content_classes %>">
  <% unless has_search_parameters? %>
    <%# if there are no input/search related params, display the "home" partial -%>
    <%= render 'home' %>
    <%= render 'shared/sitelinks_search_box' %>
  <% else %>
    <%= render 'search_results' %>
  <% end %>
</div>

app/views/catalog/show.html.erb
<div id="content" class="<%= show_content_classes %>">
  <%= render_document_main_content_partial %>
</div>

<div id="sidebar" class="<%= show_sidebar_classes %>">
   <%= render_document_sidebar_partial %>
</div>